// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxz3gojsTBZP_wo05gz7mXYjjM6RXtylc',
    appId: '1:869607421583:web:e1c0df635d9a44fe7062fa',
    messagingSenderId: '869607421583',
    projectId: 'tracktion-mcuve',
    authDomain: 'tracktion-mcuve.firebaseapp.com',
    storageBucket: 'tracktion-mcuve.appspot.com',
    measurementId: 'G-L6Y81TTN05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ0UzNO2w2zKxO5iPtqGwZrHAHj73blFg',
    appId: '1:869607421583:android:1d408c02a080fa9d7062fa',
    messagingSenderId: '869607421583',
    projectId: 'tracktion-mcuve',
    storageBucket: 'tracktion-mcuve.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkWhfrqvhHYz-2Y0OZqQEyoPdnqR9QqVg',
    appId: '1:869607421583:ios:4465cf274f3fd7167062fa',
    messagingSenderId: '869607421583',
    projectId: 'tracktion-mcuve',
    storageBucket: 'tracktion-mcuve.appspot.com',
    androidClientId: '869607421583-42vbfl9ol64gpa40io51c6ekjrg0cur3.apps.googleusercontent.com',
    iosClientId: '869607421583-negh177o2v0k57o0a9i2bj7t7dbo8gv1.apps.googleusercontent.com',
    iosBundleId: 'com.tracktion.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkWhfrqvhHYz-2Y0OZqQEyoPdnqR9QqVg',
    appId: '1:869607421583:ios:4465cf274f3fd7167062fa',
    messagingSenderId: '869607421583',
    projectId: 'tracktion-mcuve',
    storageBucket: 'tracktion-mcuve.appspot.com',
    androidClientId: '869607421583-42vbfl9ol64gpa40io51c6ekjrg0cur3.apps.googleusercontent.com',
    iosClientId: '869607421583-negh177o2v0k57o0a9i2bj7t7dbo8gv1.apps.googleusercontent.com',
    iosBundleId: 'com.tracktion.app',
  );
}
