import 'package:tracktion/models/db/database.dart';
import 'package:tracktion/models/tables/Routines.dart';

List<RoutineSetCompanion> routineSetsMigration = [
  // PPL Push 1
  RoutineSetData(
    id: 1,
    routineId: 1,
    exerciseId: 2,
    copyMethod: CopyMethod.Percentage,
    exerciseName: "Barbell Bench Press",
    notes: "",
    targetRpe: 8,
    series: 3,
    percentage: 0.8,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 2,
    routineId: 1,
    exerciseId: 6,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Incline Dumbbell Press",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 3,
    routineId: 1,
    exerciseId: 16,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Dips",
    notes: "",
    targetRpe: 8,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 4,
    routineId: 1,
    exerciseId: 17,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Cable Crossover",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 5,
    routineId: 1,
    exerciseId: 45,
    copyMethod: CopyMethod.Previous,
    exerciseName: "SkullCrushers",
    notes: "",
    targetRpe: 10,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 6,
    routineId: 1,
    exerciseId: 1,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Barbell Bench Press",
    notes: "",
    targetRpe: 8,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 7,
    routineId: 1,
    exerciseId: 12,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Lateral Rise",
    notes: "",
    targetRpe: 10,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 8,
    routineId: 1,
    exerciseId: 35,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Ab-Wheel Rollout",
    notes: "",
    targetRpe: 8,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  // PPL Pull 1
  RoutineSetData(
    id: 9,
    routineId: 2,
    exerciseId: 9,
    copyMethod: CopyMethod.Static,
    exerciseName: "Lat PullDown",
    notes: "",
    targetRpe: 8,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 10,
    routineId: 2,
    exerciseId: 8,
    copyMethod: CopyMethod.Percentage,
    exerciseName: "Pull Up",
    notes: "",
    targetRpe: 8,
    series: 3,
    percentage: 0.8,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 11,
    routineId: 2,
    exerciseId: 31,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Pendlay Row",
    notes: "",
    targetRpe: 8,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 12,
    routineId: 2,
    exerciseId: 11,
    copyMethod: CopyMethod.Previous,
    exerciseName: "FacePull",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 13,
    routineId: 2,
    exerciseId: 14,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Barbell Curl",
    notes: "",
    targetRpe: 10,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  // PPL Legs 1
  RoutineSetData(
    id: 14,
    routineId: 3,
    exerciseId: 3,
    copyMethod: CopyMethod.Percentage,
    exerciseName: "Squat",
    notes: "",
    targetRpe: 9,
    series: 4,
    percentage: 0.9,
    repmax: 120,
  ).toCompanion(true),
  RoutineSetData(
    id: 15,
    routineId: 3,
    exerciseId: 47,
    copyMethod: CopyMethod.Smart,
    exerciseName: "Romanian DeadLift",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 16,
    routineId: 3,
    exerciseId: 20,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Hip Trust",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 17,
    routineId: 3,
    exerciseId: 29,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Walking Lunge",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 18,
    routineId: 3,
    exerciseId: 48,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Cable Pull-Through",
    notes: "",
    targetRpe: 8,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 19,
    routineId: 3,
    exerciseId: 27,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Standing Calf Raise",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  // PPL Push 2
  RoutineSetData(
    id: 20,
    routineId: 4,
    exerciseId: 49,
    copyMethod: CopyMethod.Percentage,
    exerciseName: "Close Grip BenchPress",
    notes: "",
    targetRpe: 8,
    series: 3,
    percentage: 0.8,
    repmax: 100,
  ).toCompanion(true),
  RoutineSetData(
    id: 21,
    routineId: 4,
    exerciseId: 49,
    copyMethod: CopyMethod.Percentage,
    exerciseName: "OverHeadPress",
    notes: "",
    targetRpe: 8,
    series: 3,
    percentage: 0.8,
    repmax: 60,
  ).toCompanion(true),
  RoutineSetData(
    id: 22,
    routineId: 4,
    exerciseId: 6,
    copyMethod: CopyMethod.Smart,
    exerciseName: "Incline Dumbbell Press",
    notes: "",
    targetRpe: 8,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 23,
    routineId: 4,
    exerciseId: 50,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Pec Deck",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 24,
    routineId: 4,
    exerciseId: 12,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Lateral Rise",
    notes: "",
    targetRpe: 10,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 25,
    routineId: 4,
    exerciseId: 44,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Triceps KickBacks",
    notes: "",
    targetRpe: 10,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 26,
    routineId: 4,
    exerciseId: 40,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Cable Chop",
    notes: "",
    targetRpe: 10,
    series: 2,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  //  PPL Pull 2
  RoutineSetData(
    id: 27,
    routineId: 5,
    exerciseId: 51,
    copyMethod: CopyMethod.Previous,
    exerciseName: "1 Arm LatPullDown",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 28,
    routineId: 5,
    exerciseId: 8,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Pull Up",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 29,
    routineId: 5,
    exerciseId: 33,
    copyMethod: CopyMethod.Static,
    exerciseName: "T Bar Row",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 30,
    routineId: 5,
    exerciseId: 13,
    copyMethod: CopyMethod.Static,
    exerciseName: "UpRight Row",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 31,
    routineId: 5,
    exerciseId: 14,
    copyMethod: CopyMethod.Static,
    exerciseName: "Barbell Curl",
    notes: "",
    targetRpe: 10,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  // PPL Legs 2
  RoutineSetData(
    id: 32,
    routineId: 6,
    exerciseId: 28,
    copyMethod: CopyMethod.Percentage,
    exerciseName: "Sumo DeadLift",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: 0.85,
    repmax: 160,
  ).toCompanion(true),
  RoutineSetData(
    id: 33,
    routineId: 6,
    exerciseId: 7,
    copyMethod: CopyMethod.Static,
    exerciseName: "Front Squad",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 34,
    routineId: 6,
    exerciseId: 52,
    copyMethod: CopyMethod.Static,
    exerciseName: "Leg Extension",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 35,
    routineId: 6,
    exerciseId: 19,
    copyMethod: CopyMethod.Previous,
    exerciseName: "Seated Leg Curl",
    notes: "",
    targetRpe: 8,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  RoutineSetData(
    id: 36,
    routineId: 6,
    exerciseId: 23,
    copyMethod: CopyMethod.Smart,
    exerciseName: "Leg Press",
    notes: "",
    targetRpe: 9,
    series: 3,
    percentage: null,
    repmax: null,
  ).toCompanion(true),
  // UpperLower Upper 1
];
